
services:

  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=imagineriaWeb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    ports:
      - "5555:5432"